# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
title                    : "Sheila Chebii | Software Developer"
title_separator          : "-"
name                     : &name "Sheila Chebii"
description              : &description "Software developer with a passion for problem-solving and delivering innovative solutions. Known for strong work ethic, adaptability, and collaborative mindset. Specializes in Python, JavaScript, and web development."
url                      : https://sheilachebii.github.io # Updated to match your GitHub username
baseurl                  : ""
repository               : "Chebii55/academicpages.github.io"

# Site Author
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Sheila Chebii"
  pronouns         : "she/her"
  bio              : "Software developer passionate about problem-solving and delivering innovative solutions. Specializes in Python, JavaScript, Flask, React.js, and Vue.js. Known for strong work ethic, adaptability, and collaborative mindset."
  location         : "Kenya"
  employer         : "Lish AI Labs (Software Developer Intern)"
  email            : "sheilachebii55@gmail.com"
  phone            : "+254 796 796 496"
  
  # Remove or update these academic links as they may not be relevant
  googlescholar    : # Remove if not applicable
  orcid            : # Remove if not applicable
  researchgate     : # Remove if not applicable
  
  # Social/Professional links
  github           : "Chebii55"
  linkedin         : "sheila-chebii-6b914327a"
  
  # Social media - update or remove as needed
  twitter          : # Remove if not actively used
  facebook         : # Remove if not actively used
  instagram        : # Remove if not actively used

# Publication Category - The following are the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :  # filename of teaser fallback image placed in /images/, e.g., "500x300.png"
breadcrumbs              : false # true or false
words_per_minute         : 160
future                   : true
read_more                : "disabled" # Enables or disables "Read more" links to excerpts
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # e.g., meta.discourse.org
  facebook:
    appid                :
    num_posts            : # default is 5
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  hide                   : false     # Set to true to hide the RSS feed in the footer
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
social:
  type                   : "Person"
  name                   : "Sheila Chebii"
  links:
    - "https://www.linkedin.com/in/sheila-chebii-6b914327a/"
    - "https://github.com/Chebii55"

# Analytics
analytics:
  provider               :  "false" # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# These settings control the types of collections used by the template
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  # Remove or comment out collections you won't use
  # teaching:
  #   output: true
  #   permalink: /:collection/:path/
  # publications:
  #   output: true
  #   permalink: /:collection/:path/
  # talks:
  #   output: true
  #   permalink: /:collection/:path/

# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
# paginate: 5 # Amount of posts to show
# paginate_path: /page:num/
timezone: Etc/UTC # Timezone

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
